### ISSUE TITLE
Adding a bibliography and citation section?

### ISSUE THREAD

**Issue by Maudite** [AnnaChirumbolo/dissertation_template_with_rmd#1]
Hi Anna, this looks great! I've just had a quick browse, and I just noticed that there was not a section on bibliography and citations. I have seen a few posts on this before, it might be helpful to add it in? Here's a few links to give you an idea: https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
https://rosannavanhespen.nl/rmarkdown/writing-your-thesis-with-r-markdown-2-text-citations-and-equations/
https://www.themillerlab.io/post/reference_management_in_rmarkdown/
https://ulyngs.github.io/oxforddown/cites-and-refs.html

**Comment by AnnaChirumbolo** [comment]
Hi Maude, thanks! That's true, I haven't explained anything in particular about that, but thanks for your suggestions! I'm going to look into them asap and add a little section about it :)

**Comment by AnnaChirumbolo** [comment]
Hey @Maudite, I have just finished adding the bibliography and citations section! 

I still need to fix a few things, and proofread it a little bit. 

Let me know what you think of it now :) Thanks!


Anna
