### ISSUE TITLE
Erica feedback

### ISSUE THREAD

**Issue by ericazaja** [AnnaChirumbolo/dissertation_template_with_rmd#2]
Hello @AnnaChirumbolo !

Thank you for adding me to the repo! I've downloaded the repo and I've gone through all the tutorial.
Here's my thoughts and some random feedback:

- I LOVE the idea of the tutorial. Being in my 3rd year, this comes at a very convenient time. I will definitely use this format for my dissertation. So thanks very much for sharing your knowledge.

- `number_sections: TRUE will automatically create sections that ordered according to the type of header` that **are** ordered? 

- Why do you say to leave the Rmd Untitled? Is it not better to save it giving it a name? Might be useful to mention that at some point. 

- It might be useful to mention that when you open a new Rmd, it comes with a bunch of text/code chunks, and that we should delete this before starting? (Apart from the YALM header and the first code chunk perhaps?)

- When we write these `\begin{centering} and \end{centering}` below the first code chunk, is it below the `\allsectionsfont{\centering} , \subsectionfont{\raggedright} etc` or straight after the code chunk?

- For a bunch of coding functions, might be nice to format it `like this` so that they stand out? instead of *cursive*

- At the beginning I got quite confused regarding the **order** at which to insert the different sections for the cover page. Might be useful, maybe at the end of that section, to add the full code for the front page? 

- I've attached the pdf that I created using the tutorial instructions....It's not exactly what you did! I might have just interpreted the instructions wrongly. It also doesn't collate the content of the various child documents, only the code.

[diss_cover.pdf](https://github.com/AnnaChirumbolo/dissertation_template_with_rmd/files/6147755/diss_cover.pdf)

We have a dissertation help session coming up as a CC zoom tutorial in March. If we manage to publish your tutorial by then, would you be happy for us to share your tutorial at the workshop? I think it might help a bunch of people! 

Hope the feedback is somewhat useful! Cheers for making this!
All the best ! :) 
Erica

**Comment by AnnaChirumbolo** [comment]
Hey Erica, thank you for taking the time to go over it!
You gave me really good feedback, I definitely need to do some debugging, as I thought I had checked for the output to knit correctly, but evidently it isn't as it is meant to be...! 
And sure, i'd be happy for it to be used at your cc zoom tutorial! When is it? So I have an idea of how much time I have to fix it :) thanks again for the precious feedback, and hope you're doing well x

**Comment by ericazaja** [comment]
> Hey Erica, thank you for taking the time to go over it!
> You gave me really good feedback, I definitely need to do some debugging, as I thought I had checked for the output to knit correctly, but evidently it isn't as it is meant to be...!
> And sure, i'd be happy for it to be used at your cc zoom tutorial! When is it? So I have an idea of how much time I have to fix it :) thanks again for the precious feedback, and hope you're doing well x

Amazing! It's on March 31st! So you still have plenty of time.
No worries for the feedback! Also bare in mind I could have just messed stuff up and your code could be working perfectly fine ahah! Maybe worth getting a 3rd person to check it. 
Erica

**Comment by AnnaChirumbolo** [comment]
Hey @ericazaja , I have just fixed the tutorial according to your suggestions. Please let me know what you think of it now. Thanks! xx

**Comment by ericazaja** [comment]
> Hey @ericazaja , I have just fixed the tutorial according to your suggestions. Please let me know what you think of it now. Thanks! xx

Hello @AnnaChirumbolo ! So I went through it again. It's much clearer now I think!

Another couple of minor things:

- `Erase all the content but the first code chunk (already present from the start of the document), and write the following.` This is great but maybe specify: "Erase all the content from the RMarkdown document {...} and write the following after the first code chunk."

- Maybe move the screenshot where you show how to insert a code chunk just after saying to insert a code chunk rather than after `This way, the image of the UoE logo is going to appear at the top of the page.`

- I still don't think it's super clear that `\end{centering}` should be right at the bottom of the first page. I get it from the summary code, but not from the explanation. Maybe add a sentence saying that  `\end{centering}` should be at the bottom? 

- I still think mentioning saving the Rmd as `main.Rmd` would be good at some point.

That's it ! It's so so cool Anna ! 
Sono contenta perchè adesso ho già il template per la mia tesi ;)))
[diss_template.pdf](https://github.com/AnnaChirumbolo/dissertation_template_with_rmd/files/6164253/diss_template.pdf)
Thank you SO much for this !!! People will be so greatful. 

Hope we can get it published soon. I've asked other CC people if they have some time to take a look. 
Erica x)

**Comment by AnnaChirumbolo** [comment]
Hey @ericazaja , just fixed the tutorial according to these last suggestions. 

I had written this 
`So, first thing we are going to do is create the **main.Rmd** file (**you can name the file like this, if you wish**).`

to indicate that the main file name is going to be called main.Rmd, but now I put the sentence in bold so maybe it stands out more. 

Thanks again for the help, much appreciated! 

Hopefully now it's better than before :)
