### ISSUE TITLE
Hide folders

### ISSUE THREAD

**Issue by AnnaChirumbolo** [AnnaChirumbolo/dissertation_template_with_rmd#3]
Hi, I was wondering if anyone could tell me how to hide folders that are not necessary for the tutorial. 

I have distinguished the images I have used inside the tutorial from the one image that users need to upload. How can I hide or remove the "screenshots" folder? 
Thanks ! :)

**Comment by ericazaja** [comment]
Hey @AnnaChirumbolo , so I think that you'll get a new repo for your tutorial where you'll upload only the stuff that the users need to complete the tutorial (data etc). So not including all the stuff you are saying you'd like to hide. It will be a public repo that people are linked to at the start of the tutorial. I think @gndaskalova or @EliseGallois could set that up for you via the CC organisation? At least this is what I did for my tutorial! 

Erica

**Comment by EliseGallois** [comment]
Hi @AnnaChirumbolo 

Yep, you'll get a new repo in Coding Club where you can include only the necessary documents. I'm not actually 100% on the protocol for making these? @boyan-kar did you set yours up on the CC repo? If so, how was that done?

All the best,
Elise

**Comment by gndaskalova** [comment]
Hey team,

I made the repos in the past, Elise now that you are admin you can make new repos too (and maybe any member can make them, could try it Anna). The "protocol" is stick to the naming convention (you can see the ones in the past, e.g. CC-mixed-models) and add the link to the tutorial in the readme, the license statement, credits for the data if any, contact details (the CC email) and I think that's it - basically check out an existing one and copy that.

Hope you are all doing well,
Gergana

**Comment by AnnaChirumbolo** [comment]
Great, cheers!!! I'm not sure I can make a new repo in coding club, not sure i have access to it. :)

**Comment by gndaskalova** [comment]
I have just invited you @AnnaChirumbolo .

**Comment by AnnaChirumbolo** [comment]
> I have just invited you @AnnaChirumbolo .

Yes, great - thanks!
