### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EliseGallois** [AnnaChirumbolo/dissertation_template_with_rmd#4]
Hi @AnnaChirumbolo!

The tutorial looks great! I have some very minor feedback, which hopefully won't take long to implement:
- Clear aims and well organised steps: really organised tutorial, well done!
- Instead of the ‘first thing to do is download the tutorial repo’ line, I’d replace with the standard coding club box section that reads: “Аll the files you need to complete this tutorial can be downloaded from this Github repository [link]. Clone and download the repo as a zip file, then unzip it.”
- ’The School of Geosciences provides standard formatting rules’ - good, but rephrase to acknowledge that other unis will have their own rules, but in the case of this tutorial we’re following guidelines from Edinburgh GeoSciences
- You could also mention here that lots of journals etc have their own templates that you can download from their ‘Authors information’ pages - useful stuff to know for those publishing their work after diss!
- I like that you’ve hyperlinked the useful functions from the packages!
- ‘Knitr is the only most important package used in Rmarkdown’ - I’d remove the word only
- I’d also introduce Knitr slightly earlier to show people that they can knit repeatedly and check to see how their formatting has changed
- I didn’t know about child documents, thats really cool!
- In 6. Final tips, point three has a typo “plan the strcuture”
- Nice touch to link to your own dissertation!

**Comment by AnnaChirumbolo** [comment]
hi @EliseGallois , thanks for looking at it! I have just edited it according to your suggestions, cheers :)
