### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Maudite** [AnnaChirumbolo/dissertation_template_with_rmd#5]
Hi @AnnaChirumbolo!

Thank you for all your work, it's a very useful tutorial! And it's great that you have added the bibliography section too!

Here's a few suggestions to make the tutorial easier to navigate:

-I would add bibliography on line 46, when you list the sections of a scientific report, and maybe add the bibliography packages in the YAML at the beginning already

-You could add a sentence like "If you are new to rmarkdown, you might find our other rmarkdown tutorial useful" and incude a link to the other rmarkdown tutorial

-I would add details on tinytex, what is it and the installation with links at the beginning. You should not need to instal LaTex with tinytex (it uses tex live).

-maybe once the first page is done, it would be useful to explain how to knit to get an idea of what the document looks like and that it might take a few moments the first time, and maybe something about how to check the error log when it doesn't work (knitting pdf can be quite buggy at first!)

It's a great tutorial though! Thanks again, and I've learnt a lot of new things doing it!

**Comment by AnnaChirumbolo** [comment]
Thanks @Maudite for the suggestions! Will get to it asap :)

**Comment by AnnaChirumbolo** [comment]
@Maudite  done! Let me know what you think of it now :) thanks a lot!
