### ISSUE TITLE
Feedback from Boyan

### ISSUE THREAD

**Issue by boyan-kar** [AnnaChirumbolo/dissertation_template_with_rmd#6]
Excellent tutorial, @AnnaChirumbolo, and most issues were probably already addressed by other feedback givers so I'll just mention a few very small things:

- Maybe include 1-2 more sentences about the YAML language, or maybe just a link with further details where it is first mentioned and then in resources? 
- Can you also remove installing LaTeX from Final tips and Resources section (only tinytex is sufficient)?
- Would highly recommend linking to the R Markdown Cookbook, maybe even to specific chapters in specific parts of the tutorial because it is an amazing resource. https://bookdown.org/yihui/rmarkdown-cookbook/

I think we can publish the tutorial on the CC website by the end of the week if that's ok with everyone! I think it would be a great addition.

**Comment by Maudite** [comment]
Sounds good, if that's ok with you @boyan-kar! I was just going to point out the same thing about point 2 of the final tips, and maybe removing the final link about installing LaTex at the end, and finally updating the YAML of the full front page code before section 1 b). 

I thinks it's going to be a useful tutorial @AnnaChirumbolo!

**Comment by AnnaChirumbolo** [comment]
you guys are eagle-eyed! Thanks so much for your precious feedback!!
I have just pushed my final adjustments following your suggestions x
