### ISSUE TITLE
created new repo in coding club org

### ISSUE THREAD

**Issue by AnnaChirumbolo** [AnnaChirumbolo/dissertation_template_with_rmd#7]
Hi guys, I have just created the new repo in the CC org!

[Here it is](https://github.com/ourcodingclub/CC-diss-rmd) ;) 

I have kept only the things that are necessary for the tutorial, but I was not sure what to do with my `index.md` file... @boyan-kar how is that dealt with not to show in the repo? I see that all the other repos don't show it.

Let me know if there's anything else that needs fixing and I will update the repo!

Cheers :)

**Comment by AnnaChirumbolo** [comment]
Oh I also have left the link to the tutorial blank in the README.md file, for the time being

**Comment by boyan-kar** [comment]
> 
> 
> Hi guys, I have just created the new repo in the CC org!
> 
> [Here it is](https://github.com/ourcodingclub/CC-diss-rmd) ;)
> 
> I have kept only the things that are necessary for the tutorial, but I was not sure what to do with my `index.md` file... @boyan-kar how is that dealt with not to show in the repo? I see that all the other repos don't show it.
> 
> Let me know if there's anything else that needs fixing and I will update the repo!
> 
> Cheers :)

Hey @AnnaChirumbolo 

I think it's just fine to remove the index.md from the repo in the ourcodingclub organisation, and keep it in this repo. In the repo in the coding club organisation, only keep files that you want people to download when doing the tutorial. The tutorial itself will be added to the website repository.

**Comment by AnnaChirumbolo** [comment]
Ahhh right, I see!!! Thanks for the clarification, @boyan-kar :)
