### ISSUE TITLE
Tutorial up soon on CC website

### ISSUE THREAD

**Issue by boyan-kar** [AnnaChirumbolo/dissertation_template_with_rmd#8]
Hi @AnnaChirumbolo and everyone following:

The tutorial should soon be accessible at https://ourcodingclub.github.io/tutorials/rmarkdown-dissertation (once my pull request is merged). I've not added it to the Tutorials page, just so we first make sure everything is as it's supposed to be.

Here's a few final points, once the tutorial is accessible at the link:

1. I've added an Introduction section so that the tutorial follows the same structure as other CC tutorials. Let me know if that's ok and if I need to change anything.
2. I've also added a secondary title as all CC tutorials have one. Let me know if you prefer another title.
3. For now, the pictures have the original links you put in (assuming to the pictures in this repo, so don't remove it for now!). I will ideally move the pictures and the links to the website repo, but in order to publish the tutorial ASAP I have left it as is for now as it doesn't make a difference to users.
4. Would you like to make a hexagonal icon for the tutorial? I am happy to make it as well.
5. Let me know if there are any other changes that need to be made.

Great work, it will be a great addition!

**Comment by AnnaChirumbolo** [comment]
Hi @boyan-kar , thank you for doing this!!! 
Both introduction section and subtitle look great. I'm not sure I understand point 3... Do I need to change the format to which I linked the pictures shown in the tutorial? Let me know and I can fix it asap. 

It'd be very nice to make the hexagonal logo, I have not thought of anything yet, so if you have go on with your idea! I'm sure it'll look great :)

5. No more changes to be made from my part, unless someone else has any other feedback and suggestions to share ! 

Thank you and thanks for your great work with publishing it!!!

**Comment by boyan-kar** [comment]
> 
> 
> Hi @boyan-kar , thank you for doing this!!!
> Both introduction section and subtitle look great. I'm not sure I understand point 3... Do I need to change the format to which I linked the pictures shown in the tutorial? Let me know and I can fix it asap.
> 
> It'd be very nice to make the hexagonal logo, I have not thought of anything yet, so if you have go on with your idea! I'm sure it'll look great :)
> 
>     1. No more changes to be made from my part, unless someone else has any other feedback and suggestions to share !
> 
> 
> Thank you and thanks for your great work with publishing it!!!

Hi @AnnaChirumbolo 

Thanks for the quick reply.

For point 3, I meant that images in the index.md file are in this format 
`![knit_button](https://user-images.githubusercontent.com/43357858/112044413-17ea3d80-8b4a-11eb-8c02-43a4640ee5e7.jpg)`, i.e. they link to the images in this repository (I assume). To transfer the tutorial to the CC website, I took the index.md file and changed a few things to make it work with that particular website. The hyperlinks for the images are the same, and therefore they appear in the webpage, as you have seen, as long as they still exist at the same location (this repo). Next week I will copy the images to the appropriate folder in the CC repo and change the links, but for now this is fine.

Regarding the hex icon, I don't have any particular idea, but I'll come up with something (I've already made icons for the ANOVA and for the Packages tutorials, if you are interested in my amazing graphic design skills). Definitely go ahead if you have your own idea, or let me know your idea and I can do my best.

Otherwise, great that you are happy with it, the tutorial is ready to be published once an icon has been made!

**Comment by AnnaChirumbolo** [comment]
Hi @boyan-kar that's great! 

I understand what you mean now, about the pictures. 

I'll have a think about the icon and will let you know!

**Comment by boyan-kar** [comment]
> 
> 
> Hi @boyan-kar that's great!
> 
> I understand what you mean now, about the pictures.
> 
> I'll have a think about the icon and will let you know!

Hi @AnnaChirumbolo 

The tutorial is now up on the Tutorials page! It's listed under Reproducible research of course.
I also felt inspired and I already made an icon, but if you have a better idea feel free to let me know!

**Comment by AnnaChirumbolo** [comment]
Hey @boyan-kar , the logo looks great! I'm very happy with your idea so let's keep it!!! Thanks again for putting it up and running! I just noticed that I left the banner of the tutorial within the index.md so I'd perhaps remove it? Can I edit the file from here or how does it work now that the site is live? Thanks !!! ;)

**Comment by boyan-kar** [comment]
> 
> 
> Hey @boyan-kar , the logo looks great! I'm very happy with your idea so let's keep it!!! Thanks again for putting it up and running! I just noticed that I left the banner of the tutorial within the index.md so I'd perhaps remove it? Can I edit the file from here or how does it work now that the site is live? Thanks !!! ;)

Hey @AnnaChirumbolo 

I'm glad you like the logo! I'll remove the banner, no worries. The markdown file is different on the website as quite a few things had to be changed for it to work with that website, so it won't change anything if you edit it here. 
If you need anything else changes just let me know.

**Comment by AnnaChirumbolo** [comment]
Alright fair, thanks for doing it then! :) Have a good weekend x

**Comment by AnnaChirumbolo** [comment]
@boyan-kar I actually just noticed something else... The link in section 5. let's merge no longer works...! 

It was the pdf output I had linked from this repo, so maybe that has to be moved too..? Right now it's in the output folder, called output.pdf

Thanks

**Comment by boyan-kar** [comment]
> 
> 
> @boyan-kar I actually just noticed something else... The link in section 5. let's merge no longer works...!
> 
> It was the pdf output I had linked from this repo, so maybe that has to be moved too..? Right now it's in the output folder, called output.pdf
> 
> Thanks

Hey @AnnaChirumbolo 

I didn't notice that, sorry!

I think it would be best to copy the output.pdf file to the [CC-diss-rmd](https://github.com/ourcodingclub/CC-diss-rmd) repo, and I will change the link in the webpage?

Cheers

**Comment by AnnaChirumbolo** [comment]
No worries at all! 

Yes, sounds good. Will do it asap .
